- project:
    templates:
      - check-requirements
      - horizon-cross-jobs
      - horizon-nodejs10-jobs
      - horizon-non-primary-django-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-wallaby-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - horizon-selenium-headless
        - horizon-integration-tests
        - horizon-dsvm-tempest-plugin
        - horizon-tox-bandit-baseline
        - horizon-tempest-plugin-ipv6
    gate:
      queue: horizon
      jobs:
        - horizon-dsvm-tempest-plugin
        - horizon-selenium-headless
        - horizon-integration-tests
        - horizon-tempest-plugin-ipv6
    experimental:
      jobs:
        - horizon-integration-tests-xstatic-master
        - horizon-tox-py36-xstatic-master
        - horizon-nodejs10-run-test-xstatic-master
    periodic:
      jobs:
        - horizon-nodejs10-run-test
        - horizon-integration-tests
